site_name: Signal Editor Help
site_url: https://fred-kr.github.io/
repo_url: https://github.com/fred-kr/signal-editor-v2
theme:
  name: material
  palette:
    primary: "royalblue"
    accent: "navy"
    background: "floralwhite"
nav:
  - Home: index.md
  - 'User Guide':
    - 'Introduction': 'user_guide/introduction.md'
    - 'Loading Data': 'user_guide/loading_data.md'
    - 'Sections': 'user_guide/sections.md'
    - 'Signal Preprocessing': 'user_guide/signal_preprocessing.md'
    - 'Peak Detection': 'user_guide/peak_detection.md'
    - 'Exporting Results': 'user_guide/exporting_results.md'
    - 'Configuration': 'user_guide/configuration.md'
  - 'UI Components':
    - 'Menu Bar': 'ui_components/menu_bar.md'
    - 'Section List': 'ui_components/section_list.md'
    - 'Parameter Inputs': 'ui_components/parameter_inputs.md'
    - 'Status Log': 'ui_components/status_log.md'
  - About:
    - 'License': 'about/license.md'
    - 'References': 'about/references.md'