site_name: Signal Editor Documentation
site_url: https://fred-kr.github.io/
theme:
  name: material
  palette:
    primary: "royalblue"
    accent: "navy"
    background: "floralwhite"
nav:
  - Home: index.md
  - About: about.md
  - References: references.md