site_name: Signal Editor Documentation
site_url: https://fred-kr.github.io/
theme:
  name: material
  palette:
    primary: "blue"
    accent: "light blue"
    background: "white"
nav:
  - Home: index.md
  - About: about.md