[tool.poetry]
name = "signal-editor-v2"
version = "0.1.0"
description = ""
authors = ["Frederik Krämer <frdrkkraemer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pyarrow = "^17.0.0"
pyopengl-accelerate = "^3.1.7"
wfdb = "^4.1.2"
polars = "^1.4.1"
pyopengl = "^3.1.7"
mne = "^1.7.1"
pywavelets = "^1.6.0"
numpy = "==1.26.4"
scipy = "^1.14.0"
xlsxwriter = "^3.2.0"
xlsx2csv = "^0.8.3"
python-dateutil = "^2.9.0.post0"
tables = {version = "^3.9.2", allow-prereleases = true}
numexpr = "^2.10.1"
numba = "^0.60.0"
pyqtgraph = {git = "https://github.com/pyqtgraph/pyqtgraph.git", rev = "master"}
superqt = "^0.6.7"
loguru = "^0.7.2"
neurokit2 = "0.2.9"
qtconsole = "^5.5.2"
pyside6 = "^6.7.2"
darkdetect = "^0.8.0"
pyside6-fluent-widgets = {extras = ["full"], version = "^1.6.0"}
attrs = "^24.2.0"
ts2vg = "^1.2.4"

[tool.poetry.group.dev.dependencies]
ipython = "^8.26.0"
pyinstaller = "^6.9.0"
pyinstaller-hooks-contrib = "^2024.7"
sourcery = "^1.21.0"
ruff = "^0.5.7"
python-dotenv = "^1.0.1"
pytest = "^8.3.2"
# hypothesis = {extras = ["numpy"], version = "^6.102.4"}
rich = {extras = ["jupyter"], version = "^13.7.1"}
mkdocs-material = "^9.5.31"
pyright = "^1.1.375"
jedi = "^0.19.1"
pyside6-examples = "^6.7.2"
xmltodict = "^0.13.0"

[tool.ruff]
target-version = "py312"
show-fixes = true
output-format = "concise"
line-length = 120

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint]
ignore = ["E501"]
select = ["E", "F", "B"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.pyright]
pythonVersion = "3.12"
reportMissingTypeStubs = false
reportUnknownMemberType = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
