import enum

from PySide6 import QtGui

class IconBase:
    def path(self) -> str:
        raise NotImplementedError

    def icon(self) -> QtGui.QIcon:
        return QtGui.QIcon(self.path())

class FugueIcon(IconBase, enum.Enum):
    APP_AB = "app_ab"
    APP_DOCS = "app_docs"
    APP_FILE_EXPORT = "app_file_export"
    APP_MONITOR = "app_monitor"
    APP_PLUS = "app_plus"
    APP_PLUS_BLACK = "app_plus_black"
    APP_PLUS_RED = "app_plus_red"
    APP_WAVE = "app_wave"
    ARROW_RESIZE = "arrow_resize"
    ARROW_RIGHT = "arrow_right"
    AUTO_REFRESH = "auto_refresh"
    BINOCULARS = "binoculars"
    CATEGORY = "category"
    CATEGORY_ITEM = "category_item"
    CLEAR_HISTORY = "clear_history"
    COLOR = "color"
    COLOR_EDIT = "color_edit"
    COLOR_PALETTE = "color_palette"
    CREATE = "create"
    CRITICAL = "critical"
    CROSS = "cross"
    CROSS_CLOSE = "cross_close"
    DELETE = "delete"
    DOCUMENT_GO = "document_go"
    DOWNLOAD_DATA = "download_data"
    EDIT = "edit"
    EDIT_HISTORY = "edit_history"
    EDIT_REDO = "edit_redo"
    EDIT_UNDO = "edit_undo"
    ERASER = "eraser"
    ERROR = "error"
    EXPAND_MINUS = "expand_minus"
    EXPAND_PLUS = "expand_plus"
    EYE_ADD = "eye_add"
    EYE_CLOSE = "eye_close"
    EYE_OPEN = "eye_open"
    EYE_REMOVE = "eye_remove"
    FILE_EXPORT = "file_export"
    FILE_IMPORT = "file_import"
    FILTER = "filter"
    FILTER_EDIT = "filter_edit"
    FOLDER_CLOSE = "folder_close"
    FOLDER_EXPORT = "folder_export"
    FOLDER_IMPORT = "folder_import"
    FOLDER_OPEN = "folder_open"
    INFO = "info"
    INFO_BTN = "info_btn"
    LAYER = "layer"
    LAYER_ADD = "layer_add"
    LAYER_REMOVE = "layer_remove"
    LIST_VIEW = "list_view"
    LOCATION = "location"
    MINUS = "minus"
    MINUS_CIRCLE = "minus_circle"
    NAV_LEFT = "nav_left"
    NAV_LEFT_BTN = "nav_left_btn"
    NAV_RIGHT = "nav_right"
    NAV_RIGHT_BTN = "nav_right_btn"
    NAVIGATION = "navigation"
    NEW_SECTION = "new_section"
    NO_ACCESS = "no_access"
    PROCESSOR = "processor"
    PROPERTIES = "properties"
    PROPERTIES_EXPORT = "properties_export"
    PROPERTIES_IMPORT = "properties_import"
    QUESTION = "question"
    QUESTION_BTN = "question_btn"
    REFRESH = "refresh"
    REPORT = "report"
    RESET_ALL = "reset_all"
    RESOURCE_MONITOR = "resource_monitor"
    RESTORE_DEFAULTS = "restore_defaults"
    SEARCH = "search"
    SEARCH_EDIT = "search_edit"
    SEARCH_MINUS = "search_minus"
    SEARCH_PLUS = "search_plus"
    SECTION_ADD = "section_add"
    SECTION_REMOVE = "section_remove"
    SECTION_VIEW = "section_view"
    STATUS_FAILURE = "status_failure"
    STATUS_READY = "status_ready"
    STATUS_SUCCESS = "status_success"
    STATUS_WORKING = "status_working"
    SUCCESS = "success"
    SYS_MONITOR = "sys_monitor"
    SYS_MONITOR_EDIT = "sys_monitor_edit"
    TABLE_EDIT = "table_edit"
    TABLE_EXPORT = "table_export"
    TABLE_GO = "table_go"
    TABLE_IMPORT = "table_import"
    TARGET = "target"
    TARGET_ADD = "target_add"
    TARGET_EDIT = "target_edit"
    TARGET_GO = "target_go"
    TARGET_REMOVE = "target_remove"
    TERMINAL = "terminal"
    TICK_BUTTON = "tick_button"
    TICK_MARK = "tick_mark"
    TOGGLE_AUTOSCALE = "toggle_autoscale"
    TOGGLE_SPECTRUM = "toggle_spectrum"
    TOOLBOX = "toolbox"
    TOOLBOX_EDIT = "toolbox_edit"
    UPLOAD_DATA = "upload_data"
    USER_GUIDE = "user_guide"
    VIEW_DATA = "view_data"
    VIEW_RESULT = "view_result"
    VIEW_SETTINGS = "view_settings"
    WARNING = "warning"
    WARNING_TRIANGLE = "warning_triangle"
    WHATS_THIS = "whats_this"
    ZOOM_FIT = "zoom_fit"
    ZOOM_IN = "zoom_in"
    ZOOM_OUT = "zoom_out"
    MENU = "menu"
    MENU_BLUE = "menu_blue"

    def path(self) -> str:
        return f":/icons/{self.value}"
