import enum

from PySide6 import QtGui

# APP_ICON = QtGui.QIcon(":/icons/app_icon.svg")


class IconBase:
    def path(self) -> str:
        raise NotImplementedError

    def icon(self) -> QtGui.QIcon:
        return QtGui.QIcon(self.path())


# class FugueIcon(IconBase, enum.Enum):
#     APP_AB = "app_ab"
#     APP_DOCS = "app_docs"
#     APP_FILE_EXPORT = "app_file_export"
#     APP_MONITOR = "app_monitor"
#     APP_PLUS = "app_plus"
#     APP_PLUS_BLACK = "app_plus_black"
#     APP_PLUS_RED = "app_plus_red"
#     APP_WAVE = "app_wave"
#     ARROW_RESIZE = "arrow_resize"
#     ARROW_RIGHT = "arrow_right"
#     AUTO_REFRESH = "auto_refresh"
#     BINOCULARS = "binoculars"
#     CATEGORY = "category"
#     CATEGORY_ITEM = "category_item"
#     CLEAR_HISTORY = "clear_history"
#     COLOR = "color"
#     COLOR_EDIT = "color_edit"
#     COLOR_PALETTE = "color_palette"
#     CREATE = "create"
#     CRITICAL = "critical"
#     CROSS = "cross"
#     CROSS_CLOSE = "cross_close"
#     DELETE = "delete"
#     DOCUMENT_GO = "document_go"
#     DOWNLOAD_DATA = "download_data"
#     EDIT = "edit"
#     EDIT_HISTORY = "edit_history"
#     EDIT_REDO = "edit_redo"
#     EDIT_UNDO = "edit_undo"
#     ERASER = "eraser"
#     ERROR = "error"
#     EXPAND_MINUS = "expand_minus"
#     EXPAND_PLUS = "expand_plus"
#     EYE_ADD = "eye_add"
#     EYE_CLOSE = "eye_close"
#     EYE_OPEN = "eye_open"
#     EYE_REMOVE = "eye_remove"
#     FILE_EXPORT = "file_export"
#     FILE_IMPORT = "file_import"
#     FILTER = "filter"
#     FILTER_EDIT = "filter_edit"
#     FOLDER_CLOSE = "folder_close"
#     FOLDER_EXPORT = "folder_export"
#     FOLDER_IMPORT = "folder_import"
#     FOLDER_OPEN = "folder_open"
#     INFO = "info"
#     INFO_BTN = "info_btn"
#     LAYER = "layer"
#     LAYER_ADD = "layer_add"
#     LAYER_REMOVE = "layer_remove"
#     LIST_VIEW = "list_view"
#     LOCATION = "location"
#     MINUS = "minus"
#     MINUS_CIRCLE = "minus_circle"
#     NAV_LEFT = "nav_left"
#     NAV_LEFT_BTN = "nav_left_btn"
#     NAV_RIGHT = "nav_right"
#     NAV_RIGHT_BTN = "nav_right_btn"
#     NAVIGATION = "navigation"
#     NEW_SECTION = "new_section"
#     NO_ACCESS = "no_access"
#     PROCESSOR = "processor"
#     PROPERTIES = "properties"
#     PROPERTIES_EXPORT = "properties_export"
#     PROPERTIES_IMPORT = "properties_import"
#     QUESTION = "question"
#     QUESTION_BTN = "question_btn"
#     REFRESH = "refresh"
#     REPORT = "report"
#     RESET_ALL = "reset_all"
#     RESOURCE_MONITOR = "resource_monitor"
#     RESTORE_DEFAULTS = "restore_defaults"
#     SEARCH = "search"
#     SEARCH_EDIT = "search_edit"
#     SEARCH_MINUS = "search_minus"
#     SEARCH_PLUS = "search_plus"
#     SECTION_ADD = "section_add"
#     SECTION_REMOVE = "section_remove"
#     SECTION_VIEW = "section_view"
#     STATUS_FAILURE = "status_failure"
#     STATUS_READY = "status_ready"
#     STATUS_SUCCESS = "status_success"
#     STATUS_WORKING = "status_working"
#     SUCCESS = "success"
#     SYS_MONITOR = "sys_monitor"
#     SYS_MONITOR_EDIT = "sys_monitor_edit"
#     TABLE_EDIT = "table_edit"
#     TABLE_EXPORT = "table_export"
#     TABLE_GO = "table_go"
#     TABLE_IMPORT = "table_import"
#     TARGET = "target"
#     TARGET_ADD = "target_add"
#     TARGET_EDIT = "target_edit"
#     TARGET_GO = "target_go"
#     TARGET_REMOVE = "target_remove"
#     TERMINAL = "terminal"
#     TICK_BUTTON = "tick_button"
#     TICK_MARK = "tick_mark"
#     TOGGLE_AUTOSCALE = "toggle_autoscale"
#     TOGGLE_SPECTRUM = "toggle_spectrum"
#     TOOLBOX = "toolbox"
#     TOOLBOX_EDIT = "toolbox_edit"
#     UPLOAD_DATA = "upload_data"
#     USER_GUIDE = "user_guide"
#     VIEW_DATA = "view_data"
#     VIEW_RESULT = "view_result"
#     VIEW_SETTINGS = "view_settings"
#     WARNING = "warning"
#     WARNING_TRIANGLE = "warning_triangle"
#     WHATS_THIS = "whats_this"
#     ZOOM_FIT = "zoom_fit"
#     ZOOM_IN = "zoom_in"
#     ZOOM_OUT = "zoom_out"
#     MENU = "menu"
#     MENU_BLUE = "menu_blue"

#     def path(self) -> str:
#         return f":/icons/{self.value}"


class SignalEditorIcon(IconBase, enum.Enum):
    SignalEditor = ":/icons/app_icon.svg"
    Add = ":/icons/fluent-icons/Add.svg"
    AddCircle = ":/icons/fluent-icons/AddCircle.svg"
    AddSquare = ":/icons/fluent-icons/AddSquare.svg"
    ArrowAutofitHeight = ":/icons/fluent-icons/ArrowAutofitHeight.svg"
    ArrowAutofitHeightDotted = ":/icons/fluent-icons/ArrowAutofitHeightDotted.svg"
    ArrowExportLtr = ":/icons/fluent-icons/ArrowExportLtr.svg"
    ArrowExportUp = ":/icons/fluent-icons/ArrowExportUp.svg"
    ArrowImport = ":/icons/fluent-icons/ArrowImport.svg"
    ArrowLeft = ":/icons/fluent-icons/ArrowLeft.svg"
    ArrowNext = ":/icons/fluent-icons/ArrowNext.svg"
    ArrowPrevious = ":/icons/fluent-icons/ArrowPrevious.svg"
    ArrowReset = ":/icons/fluent-icons/ArrowReset.svg"
    ArrowRight = ":/icons/fluent-icons/ArrowRight.svg"
    ArrowSync = ":/icons/fluent-icons/ArrowSync.svg"
    AutoFitHeight = ":/icons/fluent-icons/AutoFitHeight.svg"
    BookInformation = ":/icons/fluent-icons/BookInformation.svg"
    BookQuestionMark = ":/icons/fluent-icons/BookQuestionMark.svg"
    BookSearch = ":/icons/fluent-icons/BookSearch.svg"
    Broom = ":/icons/fluent-icons/Broom.svg"
    Bug = ":/icons/fluent-icons/Bug.svg"
    CaretLeft = ":/icons/fluent-icons/CaretLeft.svg"
    CaretRight = ":/icons/fluent-icons/CaretRight.svg"
    CheckboxChecked = ":/icons/fluent-icons/CheckboxChecked.svg"
    CheckboxIndeterminate = ":/icons/fluent-icons/CheckboxIndeterminate.svg"
    CheckboxUnchecked = ":/icons/fluent-icons/CheckboxUnchecked.svg"
    CheckboxWarning = ":/icons/fluent-icons/CheckboxWarning.svg"
    Checkmark = ":/icons/fluent-icons/Checkmark.svg"
    CheckmarkCircle = ":/icons/fluent-icons/CheckmarkCircle.svg"
    CheckmarkSquare = ":/icons/fluent-icons/CheckmarkSquare.svg"
    ChevronCircleDown = ":/icons/fluent-icons/ChevronCircleDown.svg"
    ChevronCircleRight = ":/icons/fluent-icons/ChevronCircleRight.svg"
    ChevronDown = ":/icons/fluent-icons/ChevronDown.svg"
    ChevronLeft = ":/icons/fluent-icons/ChevronLeft.svg"
    ChevronRight = ":/icons/fluent-icons/ChevronRight.svg"
    ChevronUp = ":/icons/fluent-icons/ChevronUp.svg"
    Circle = ":/icons/fluent-icons/Circle.svg"
    CircleEdit = ":/icons/fluent-icons/CircleEdit.svg"
    CircleHalfFill = ":/icons/fluent-icons/CircleHalfFill.svg"
    CircleLine = ":/icons/fluent-icons/CircleLine.svg"
    Code = ":/icons/fluent-icons/Code.svg"
    Color = ":/icons/fluent-icons/Color.svg"
    ConvertToTable = ":/icons/fluent-icons/ConvertToTable.svg"
    Copy = ":/icons/fluent-icons/Copy.svg"
    DataArea = ":/icons/fluent-icons/DataArea.svg"
    DataHistogram = ":/icons/fluent-icons/DataHistogram.svg"
    DataScatter = ":/icons/fluent-icons/DataScatter.svg"
    Delete = ":/icons/fluent-icons/Delete.svg"
    DeleteDismiss = ":/icons/fluent-icons/DeleteDismiss.svg"
    DesktopPulse = ":/icons/fluent-icons/DesktopPulse.svg"
    Dismiss = ":/icons/fluent-icons/Dismiss.svg"
    DismissCircle = ":/icons/fluent-icons/DismissCircle.svg"
    DismissSquare = ":/icons/fluent-icons/DismissSquare.svg"
    DocumentArrowLeft = ":/icons/fluent-icons/DocumentArrowLeft.svg"
    DocumentArrowRight = ":/icons/fluent-icons/DocumentArrowRight.svg"
    DocumentBulletListClock = ":/icons/fluent-icons/DocumentBulletListClock.svg"
    DocumentDismiss = ":/icons/fluent-icons/DocumentDismiss.svg"
    DocumentEndnote = ":/icons/fluent-icons/DocumentEndnote.svg"
    DocumentToolbox = ":/icons/fluent-icons/DocumentToolbox.svg"
    Edit = ":/icons/fluent-icons/Edit.svg"
    EditOff = ":/icons/fluent-icons/EditOff.svg"
    EditSettings = ":/icons/fluent-icons/EditSettings.svg"
    Eraser = ":/icons/fluent-icons/Eraser.svg"
    ErrorCircle = ":/icons/fluent-icons/ErrorCircle.svg"
    EyeHide = ":/icons/fluent-icons/EyeHide.svg"
    EyeShow = ":/icons/fluent-icons/EyeShow.svg"
    FolderOpen = ":/icons/fluent-icons/FolderOpen.svg"
    History = ":/icons/fluent-icons/History.svg"
    Important = ":/icons/fluent-icons/Important.svg"
    Info = ":/icons/fluent-icons/Info.svg"
    Lasso = ":/icons/fluent-icons/Lasso.svg"
    LightbulbCircle = ":/icons/fluent-icons/LightbulbCircle.svg"
    List = ":/icons/fluent-icons/List.svg"
    LockClosed = ":/icons/fluent-icons/LockClosed.svg"
    LockOpen = ":/icons/fluent-icons/LockOpen.svg"
    MoreHorizontal = ":/icons/fluent-icons/MoreHorizontal.svg"
    MoreVertical = ":/icons/fluent-icons/MoreVertical.svg"
    Navigation = ":/icons/fluent-icons/Navigation.svg"
    New = ":/icons/fluent-icons/New.svg"
    Options = ":/icons/fluent-icons/Options.svg"
    PageFit = ":/icons/fluent-icons/PageFit.svg"
    Play = ":/icons/fluent-icons/Play.svg"
    PlayCircle = ":/icons/fluent-icons/PlayCircle.svg"
    Prohibited = ":/icons/fluent-icons/Prohibited.svg"
    Pulse = ":/icons/fluent-icons/Pulse.svg"
    Question = ":/icons/fluent-icons/Question.svg"
    QuestionCircle = ":/icons/fluent-icons/QuestionCircle.svg"
    RectangleLandscape = ":/icons/fluent-icons/RectangleLandscape.svg"
    Save = ":/icons/fluent-icons/Save.svg"
    SaveArrowRight = ":/icons/fluent-icons/SaveArrowRight.svg"
    SaveEdit = ":/icons/fluent-icons/SaveEdit.svg"
    ScanObject = ":/icons/fluent-icons/ScanObject.svg"
    Search = ":/icons/fluent-icons/Search.svg"
    SearchSquare = ":/icons/fluent-icons/SearchSquare.svg"
    SearchVisual = ":/icons/fluent-icons/SearchVisual.svg"
    SelectObject = ":/icons/fluent-icons/SelectObject.svg"
    Send = ":/icons/fluent-icons/Send.svg"
    Settings = ":/icons/fluent-icons/Settings.svg"
    Status = ":/icons/fluent-icons/Status.svg"
    Subtract = ":/icons/fluent-icons/Subtract.svg"
    SubtractCircle = ":/icons/fluent-icons/SubtractCircle.svg"
    SubtractSquare = ":/icons/fluent-icons/SubtractSquare.svg"
    TabDesktopArrowClockwise = ":/icons/fluent-icons/TabDesktopArrowClockwise.svg"
    Table = ":/icons/fluent-icons/Table.svg"
    Temperature = ":/icons/fluent-icons/Temperature.svg"
    Toolbox = ":/icons/fluent-icons/Toolbox.svg"
    Warning = ":/icons/fluent-icons/Warning.svg"
    WindowDevTools = ":/icons/fluent-icons/WindowDevTools.svg"
    Wrench = ":/icons/fluent-icons/Wrench.svg"
    ZoomIn = ":/icons/fluent-icons/ZoomIn.svg"
    ZoomOut = ":/icons/fluent-icons/ZoomOut.svg"

    def path(self) -> str:
        return self.value

    @staticmethod
    def app_icon() -> QtGui.QIcon:
        return QtGui.QIcon(":/icons/app_icon.svg")
